ncclient j2config support
tbotnz/netpalm pull request #117
Opened 2020-11-05 20:30 UTC by rhwendt

This PR addresses some issues I was facing when attempting to push config using ncclient. Below is a summary of the issues I had when using this library.

- editconfig would return `Unserializable return value` from redis jobs
- lack of jinja2 templating when using ncclient

Here is a summary of the changes I am proposing.

- Move `render_json` boolean out of the `args` body making it an optional component. This allows me to render json from the reponses of getconfig and setconfig when using the ncclient library.
- `render_json` works for both getconfig and setconfig respones in the ncclient library.
- Made `args` in `NcclientSetConfig` model optional.
- Made `j2config` in `NcclientSetConfig` model optional.
- If you rendered j2config for ncclient it will add it to the `kwargs['args']['config']` dict which gets passed to ncclient.
- `ncclient_drvr.ncclien:editconfig` formats the response as xml
- added a ncclient template for pytest
- added a new method for setconfig mark for pytest `test_setconfig_ncclient_j2()`
- fixed references to `render_json` in test files.

Side note: Do you have issues with github actions failing randomly for no reason? I built it several times locally and they passed but when I ran the github actions they would fail on different errors each time and eventually it passed after running more than once?

2020-11-07 21:37 UTC, tbotnz commented
thanks for the pr @rhwendt will review tonight

2020-11-09 07:54 UTC, tbotnz commented
Would it be possible to keep _render_json_ within _args_ so that we are not changing the public API for **all** users at this point.
Whilst i completely understand the reasoning for moving it out of args i am just mindful of the impact on other users at this point. 

This is my only concern with the PR

2020-11-09 14:37 UTC, rhwendt commented
Yeah that's a fair concern. I can rework this so I don't affect everyone.

2020-11-11 20:16 UTC, rhwendt commented
Still working on this just been tied up with other things.

2020-11-11 22:09 UTC, rhwendt commented
Made `config` and `target` optional arguments in `NcclientSendConfigArgs`

**config**
This allows me to render j2config and add it to the args body after calling `exec_config`. I could have pre-rendered it using one of the other URI's but this seems like a hassle when the functionality is already in `exec_config`. If `config` is omitted ncclient will still throw an exception vs pydantic throwing one.

**target**
Already defaults to `candidate` in ncclient.

Let me know if you have any concerns.

P.S. sorry about the typo's :smile:

2020-11-16 18:48 UTC, rhwendt commented
@tbotnz This is complete, but let me know if you have any concerns. Thanks!

2020-11-17 07:40 UTC, tbotnz requested changes
Thanks for fixing this up @rhwendt much appreciated, sorry for the delay in getting back to you on this.

Can only see one minor issue below, if you fix that then happy to merge

2020-11-17 07:40 UTC, tbotnz commented on netpalm/backend/core/models/models.py
> +                "render_json": True,
plz move under args

2020-11-18 09:02 UTC, merged